### ISSUE TITLE
TreeDefinitions - DataFolderElements grouping and ordering bug

### ISSUE THREAD

**Issue by aeont** [Orckestra/C1-CMS#171] opened 2016-04-06 16:10 UTC
<DataFolderElements Type="WUBS.Resources.Data.Types.ICurrencyNews" DateFormat="yyyy MMMM" FieldGroupingName="PublishDateTime" Display="Auto" SortDirection="Descending">

3) stuff here:
1) Descending / Ascending have no effect. It's always display old dates at the top.

Minor stuff, just FYI.
2) SortDirection - it's uppercase.  If you look at:

                    <OrderBy>
                      <Field FieldName="LocalOrdering" Direction="ascending"></Field>
                    </OrderBy>

it's lower case. so Descending VS descending. Looking at others -  its upper case. 

3) it's about make things nice.. just now realized it:

![image](https://cloud.githubusercontent.com/assets/11037398/14323847/1c184292-fbd7-11e5-8bc2-ea8ea3af08ff.png)

markup is different lower case and upper case.

**Comment by wwwysocki** [comment] 2016-04-21 09:05
> Descending / Ascending have no effect. It's always display old dates at the top.

Can't reproduce it (tried on the Blog's tree definition, used 20160421.1). So I'll close this issue.
Please reopen it if you have a test scenario that can reproduce this issue.

> SortDirection - it's uppercase. If you look at... `Direction` ... it's lower case. so Descending VS descending. Looking at others - its upper case.

I've created a feature request for that - https://github.com/Orckestra/C1-CMS/issues/172

> `<ReportFunctionAction Label="..." ... >`
>   `<f:function name="..." ... >`
> markup is different lower case and upper case.

These are two different schemas. Tree definitions are based on Tree.xsd (with the uppercase). They only reuse Function.xsd (with the lowercase) used elsewahere. So it's kind of historical so :).

Anyway, I've included this inconsistency with the upper-/lowercase into the above feature request, too (https://github.com/Orckestra/C1-CMS/issues/172)

**Closed by wwwysocki** 2016-04-21 09:05 UTC

**Comment by wwwysocki** [comment] 2016-04-25 09:06
As agreed, I tried a page data folder (both dynamic and static) with a tree definition. Still, can't reproduce it. Tried on both 5.0 (offcial) and the latest build.

Please find the download links to:

1. https://dl.dropboxusercontent.com/u/11887629/Composite.Test.Notes.zip - the package with the page data folder + tree definition I used. 
2. https://dl.dropboxusercontent.com/u/11887629/Composite.Test.Note.source.zip - the source code of the page data folder type.

If possible, could please you provide your non-working example (simplified etc).
