### ISSUE TITLE
The current sitemap uses menu titles rather than page titles

### ISSUE THREAD

**Issue by wwwysocki** [Orckestra/C1-CMS#196] opened 2016-07-01 07:36 UTC
**Repro:**

1. Create a Razor function with the code below. 
2. Edit a page in the C1 Console. 
3. Change its page title (e.g "Page Title") so that it differs from its menu title (e.g. "Menu Title"). 
4. Insert the Razor function from Step 1 on the page. 
5. Preview the page.

**Expected**: The function shows the page title (e.g "Page Title") 
**Actual:** The function shows the menu title (e.g. "Menu Title").

**Code**:

```
@inherits RazorFunction 
@functions { 
public override string FunctionDescription 
{ 
get { return "..."; } 
} 
} 
<html xmlns="http://www.w3.org/1999/xhtml" xmlns:f="http://www.composite.net/ns/function/1.0"> 
<head> 
</head> 
<body> 
<p>@SiteMap.CurrentNode.Title</p> 
</body> 
</html>
```

For a workaround see my comment below.

**Comment by wwwysocki** [comment] 2016-07-01 07:42
**Workaround**:

1. Download [SiteMapUtils.cs](https://dl.dropboxusercontent.com/u/11887629/SiteMapUtils.cs).
2. Copy it to `~/App_Code`
3. In `~/Web.config`, locate `configuration/system.web/siteMap[@defaultProvider="CompositeC1"]/providers`
4. Comment the default sitemap provider and add the custom provider instead - see below.
5. Restart the server

```
<siteMap defaultProvider="CompositeC1">
  <providers>
<!--<add name="CompositeC1" type="Composite.AspNet.CompositeC1SiteMapProvider, Composite" />-->
    <add name="CompositeC1" type="Test.CustomSiteMapProvider, App_Code"/>
  </providers>
</siteMap>
```

(Alternatively, you can implement create a class library with the downloaded code, copy its DLL to `~/Bin`, and use the name of the DLL instead of 'App_Code' in the above sitemap configuration in `~/Web.config`)

Now for the sample Razor function to pick up on this workaround, change the code to:

```
@if (SiteMap.CurrentNode is Composite.AspNet.CompositeC1SiteMapNode)
{
    Test.SiteMapUtil.CurrentNode = 
	new SiteMapNode(SiteMap.Provider, CurrentPageNode.Id.ToString()) 
	{
			Title = CurrentPageNode.Title
	};
}
<p>@SiteMap.CurrentNode.Title</p>
```

**Comment by burningice2866** [comment] 2016-07-01 07:56
@wwwysocki IMHO your wrong... a SiteMap SHOULD shown the menu titles since its what you use for generating menus and navigation.

**Comment by burningice2866** [comment] 2016-07-01 07:57
if you need the Title of the page, you make a simple lookup like this

`PageManager.GetPageById(Guid.Parse(SiteMap.CurrentNode.Key)).Title`

**Comment by wwwysocki** [comment] 2016-07-01 08:18
Turned it into a feature request. 
@burningice2866 I am just documenting a requirement from a user :)

**Comment by burningice2866** [comment] 2016-07-01 10:15
@wwwysocki fair enough... as long as we're keeping track of what is actual bugs and what is 'as designed' :+1: 

Sounds to me that the user is using SiteMap wrongly if he/she expects to render a pages title using SiteMap. SiteMap is for menus and navigation.

And i'm not sure exactly what the feature request is here. If you change the code as you propose, it will have impact on sitemap.xml generation as well.

**Comment by mawtex** [comment] 2016-07-01 10:57
I think we might as well close this - as @burningice2866 says, the ASP.NET SiteMap title values should reflect menu titles, since the sitemap provider sole purpose in life is creating navigation structures. I don't see we would ever change that.

There is a native C1 API that will expose both page title and menu title - see http://api.composite.net/html/AllMembers_T_Composite_Data_SitemapNavigator.htm

**Closed by mawtex** 2016-07-01 10:57 UTC
Labels: enhancement

**Comment by ai-fwd** [comment] 2016-07-06 17:42
The above bug was created in response to a ticket created around dynamically changing page titles. The solution given was to replace the CurrentNode with a new SitemapNode with the dynamic title and then pull that out via an ASCX breadcrumb.

If that is the wrong approach based on the above then that's fine but that was the workaround provided which i guess is being retracted. Is there no way to override/create a new Composite.AspNet.CompositeC1SiteMapNode which does contain the documentTitle or an easier way to override the Title in general?

**Comment by burningice2866** [comment] 2016-07-07 10:59
@ai-fwd The issue created relates to whether SiteMapNode.Title should return the Page's Title or MenuTitle. That we agreed on is the expected behavior and shouldn't be changed.

What you do on your website is entirely up to you and you are free to either replace the SiteMapProvider entirely or add dynamic node resolving as suggested by @wwwysocki

**Comment by ai-fwd** [comment] 2016-07-08 01:50
@burningice2866 The dynamic node resolving was the workaround I came up with but I was hoping there was a cleaner way built into the product. I guess the net of it all is that there isn't right now.

**Comment by burningice2866** [comment] 2016-07-11 07:54
@ai-fwd Dynamic Node Resolving is exactly the kind of clean way you would expect to be built in. It allows for clear and clean separation of default behavior while still allowing to override it with any custom behavior that users like you might have.

PS. Since Composite internally represents a SiteMapNode using the [CompositeC1SiteMapNode ](https://github.com/Orckestra/C1-CMS/blob/master/Composite/AspNet/CompositeC1SiteMapNode.cs) class, you can eventually cast it and access DocumentTitle.

```
var node = (CompositeC1SiteMapNode)SiteMap.CurrentNode;
var menuTitle = node.Title;
var documentTitle = node.DocumentTitle;
```
